// app/layout.tsx (server component)
import type { Metadata } from "next";
import "./globals.css";
import Loader from "@/components/Loader/Loader";
import ClientLayout from "./ClientLayout/ClientLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
